#!/usr/bin/env python3
"""
Reads code_checksum.txt and data_checksum.txt (produced by compute_checksums.py)
and generates a C header that the firmware includes to report POST status.
"""
import sys
 
code_checksum = ''
data_checksum = ''
 
with open('code_checksum.txt') as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith('#'):
            code_checksum = line
            break
 
with open('data_checksum.txt') as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith('#'):
            data_checksum = line
            break
 
if not code_checksum or not data_checksum:
    print("ERROR: Could not read checksums from txt files")
    sys.exit(1)
 
with open('libraries/GCS_MAVLink/KFT_Checksums.h', 'w') as f:
    f.write('#pragma once\n')
    f.write('// AUTO-GENERATED by generate_checksum_header.py — do not edit\n')
    f.write(f'#define KFT_CODE_CHECKSUM "{code_checksum}"\n')
    f.write(f'#define KFT_DATA_CHECKSUM "{data_checksum}"\n')
 
print(f"Generated KFT_Checksums.h")
print(f"  CODE: {code_checksum}")
print(f"  DATA: {data_checksum}")
