#pragma once
// AUTO-GENERATED by generate_checksum_header.py — do not edit
#define KFT_CODE_CHECKSUM "0a728028773ee2673596b651b3bb0d17cc7dde172108c3a8aeec81a7cc98927d"
#define KFT_DATA_CHECKSUM "2193b10d27a049fe90447a9ba71684f0c974b8e94d813e37b278da3dd73488ea"
